language: node_js
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
node_js:
  - node
before_install:
  - npm i -g yarn --cache-min 999999999
install:
  - yarn
test:
  - yarn test
deploy:
  provider: npm
  email: doug@dougwade.io
  api_key:
    secure: M7FWHGbOb1PNArwQmPU23mld8HAgZ4WoYTxFPzVd4adz2X6ZXbNzaEOhgqcZ9iIcHjEk4fCK9IyiGyNsWIwo+927JH2R/f7tQ3wmnIlvnFWfmFKpwa8gG6//LwsiGwZLENK6wx2fC6949rbp+8lg1BT6yMiqcaXk8+x0avSyNus=
  on:
    tags: true
    repo: doug-wade/generator-sub
